# https://github.com/apache/infrastructure-asfyaml/blob/main/README.md

github:
  homepage: https://people.apache.org/
  description: Apache Comdev source for 'PhoneBook' website
  rulesets:
    - name: "Default Branch Protection"
      type: branch
      branches:
        includes:
          - "~DEFAULT_BRANCH"
          - "release/*"
          - "rel/*"
        excludes: []
      bypass_teams:
        - root
      restrict_deletion: true
      restrict_force_push: true
